### ISSUE TITLE
No stations found

### ISSUE THREAD

**Issue by xAPPO** [tim-hellhake/netatmo-weather-adapter#3]
I can't get anything to be discovered in new Things. How can I debug this ? I am sure my credentials are correct (although initially I entered an incorrect password which persisted even though I deleted and re-added the add-on). It seems to be correct and persists now.  

 I have the add-on and adaptor correctly listed.

**Comment by freaktechnik** [comment]
The adapter queries the netatmo API here: https://github.com/freaktechnik/netatmo-weather-adapter/blob/master/adapter.js#L204 which essentially calls https://dev.netatmo.com/en-US/resources/technical/reference/weather/getstationsdata

Please double check you gave the correct permissions to the API credentials (home automation should cover it all iirc).

If there's an error during that you should see that in the logs (Settings -> Developers -> Logs). Else this endpoint is returning an empty array.

**Comment by tim-hellhake** [comment]
@xAPPO
Any updates on this?

**Comment by tim-hellhake** [comment]
@xAPPO
I'm closing this now.
If the problems persist, please open a new issue.
